
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='pipda',
    version='0.4.5',
    description='A framework for data piping in python',
    python_requires='==3.*,>=3.7.0',
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    packages=['pipda'],
    package_dir={"": "."},
    package_data={},
    install_requires=['diot', 'executing', 'pure-eval==0.*', 'varname'],
    extras_require={"dev": ["pytest", "pytest-cov"]},
)
